name: setup semantic-release with plugins
runs:
  using: composite
  steps:
  - uses: actions/setup-node@v5
    id: setup-node
  - uses: actions/cache@v4
    with:
      path: ~/.npm
      key: ${{ runner.os }}-npm-${{ steps.setup-node.node-version }}
  - shell: bash
    run: |
      npm i -g                                  \
      semantic-release                          \
      @semantic-release/exec                    \
      @semantic-release/git                     \
      @semantic-release/changelog               \
      @google/semantic-release-replace-plugin
