branches:
  - master
  - name: ci/*
    prerelease: ci
  #- name: develop
  #  prerelease: dev
  #- name: feature/*
  #  prerelease: rc
plugins:
- '@semantic-release/commit-analyzer'
- '@semantic-release/release-notes-generator'
- '@semantic-release/changelog'
- - '@google/semantic-release-replace-plugin'
  - replacements:
    - files: [pyproject.toml]
      from: ^version = ".*?"
      to: version = "${nextRelease.version}"
      countMatches: true
      results:
      - file: pyproject.toml
        hasChanged: true
        numMatches: 1
        numReplacements: 1
- - '@semantic-release/git'
  - assets:
    - CHANGELOG.md
    - pyproject.toml
- - '@semantic-release/exec'
  - prepareCmd: poetry build
- - '@semantic-release/github'
  - assets:
      - dist/*.whl
      - dist/*.tar.gz
    branches: master
