# Allowed number of prerelease rules: 1..3
# While semantic-release allows globs, they must be combined with `prerelease: true` and suffix is derived from name than. It conflicts with PEP440 
# PEP440 version rules (not compatible with SemVer): [N!]N(.N)*[{a|b|rc}N][.postN][.devN]
# Consequences:
#   - prerelease branches must be explicitly specified, no asterisks
#   - prerelease parameter should be one of: a,b,rc,dev,post
#   - translation from SemVer prerelease notation to PEP440 is tone in 'replacements' section
branches: # only branches listed here will create releases
  - master
  - name: ci/trusted_publishing_test
    prerelease: dev
  #- name: develop
  #  prerelease: dev
  #- name: feature/*
  #  prerelease: true   # will use branch name as suffix
plugins:
- '@semantic-release/commit-analyzer'
- '@semantic-release/release-notes-generator'
- '@semantic-release/changelog'
- - '@google/semantic-release-replace-plugin'
  - replacements:
    - files: [pyproject.toml]
      from: ^version = ".*?"
      to: version = "${nextRelease.version}"
      countMatches: true
      results:
      - file: pyproject.toml
        hasChanged: true
        numMatches: 1
        numReplacements: 1
    - files: [pyproject.toml] # optional: SemVer prerelease -> PEP440  ("1.2.3-dev.1" -> "1.2.3.dev1")
      from: '^version = "(\\d+\\.\\d+\\.\\d+)-(dev|post)\\.(\\d+)"'
      to: 'version = "\\1.\\2\\3"'
    - files: [pyproject.toml] # optional: SemVer prerelease -> PEP440  ("1.2.3-rc.10" -> "1.2.3rc10" )
      from: '^version = "(\\d+\\.\\d+\\.\\d+)-(a|b|rc)\\.(\\d+)"'
      to: 'version = "\\1\\2\\3"'
- - '@semantic-release/git'
  - assets:
    - CHANGELOG.md
    - pyproject.toml
- - '@semantic-release/exec'
  - prepareCmd: |
      #!/bin/bash
      PYPI_PROJECT_NAME=${ALT_PYPI_PROJECT_NAME:-appmap}
      poetry build --config-settings name="$PYPI_PROJECT_NAME"

      if [ -n "$ALT_PYPI_PROJECT_NAME" ] ; then
        echo "Altered distribution name detected, applying Provides-Dist patch"
        WHEEL=$(ls dist/*.whl | head -n1)
        SDIST=$(ls dist/*.tar.gz | head -n1)
        for artifact in "$WHEEL" "$SDIST"; do
          TMP=$(mktemp -d)
          ARTIFACT_PATH="$artifact"
          if [[ $artifact == *.whl ]]; then
              unzip -q "$ARTIFACT_PATH" -d "$TMP"
              DISTINFO=$(find "$TMP" -type d -name "*.dist-info")
              echo "Provides-Dist: appmap" >> "$DISTINFO/METADATA"
              (cd "$TMP" && zip -qr "$ARTIFACT_PATH" .)
          else
              tar -xzf "$ARTIFACT_PATH" -C "$TMP"
              PKGDIR=$(find "$TMP" -maxdepth 1 -type d -name "*")
              echo "Provides-Dist: appmap" >> "$PKGDIR/PKG-INFO"
              (cd "$TMP" && tar -czf "$ARTIFACT_PATH" .)
          fi
          echo "(Provides-Dist: appmap): patched $ARTIFACT_PATH"
          rm -rf "$TMP"
        done
      fi
- - '@semantic-release/github'
  - assets:
      - dist/*.whl
      - dist/*.tar.gz
