name: Refetch artifacts
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: wheel
        path: ./dist
    - uses: actions/download-artifact@v4
      with:
        name: sdist 
        path: ./dist
